### ISSUE TITLE
Type not defined on geometry

### ISSUE THREAD

**Issue by alaframboise** [Esri/terraformer-arcgis-parser#25]
The type property should be defined when you convert GeoJSON to ArcGIS JSON.  Right now it's being stripped out during the "convert" process and has to be added back manually.
```
var features = new Terraformer.FeatureCollection(geojson);
var geomType = getEsriType(primitive.features[0].geometry.type);
var arcgis = Terraformer.ArcGIS.convert(features);
// apply type to all geoms...
for ( i = 0; i < arcgis.features.length; i++) {
   arcgis.features[i].geometry.type = geomType;
}
```

NOTE:  Esri geometry types are different GeoJSON and have to be mapped.

```
   function getEsriType(geometryGeoJson) {
          var type;
          switch (geometryGeoJson) {
            case "Point":
              type = "point";
            case "MultiPoint":
              type = "multipoint";
            case "Polyline":
              type = "polyline";
            case "Polygon":
              type = "polygon";
            case "MultiPolygon":
              type = "polygon";
          }
          return type;
        }
```

**Comment by patrickarlt** [comment]
Technically the ArcGIS spec doesn't define a `type` property http://resources.arcgis.com/en/help/arcgis-rest-api/#/Geometry_objects/02r3000000n1000000/ and I don't think any of the REST API services produce it.

**Comment by jgravois** [comment]
i'm with @patrickarlt on this one.  closing, but happy to discuss further if it'd be helpful.
