### ISSUE TITLE
Do not convert coordinates

### ISSUE THREAD

**Issue by steveoh** [Esri/terraformer-arcgis-parser#30]
[These lines of code](https://github.com/Esri/terraformer-arcgis-parser/blob/master/terraformer-arcgis-parser.js#L287-L289) change the spatial reference of incoming data. This only happens if and only if the data has the spatial reference wkid of 10200.

I do not think it is the job of arcgis parser to try to standardize a geometries spatial reference. Its purpose is to serialize and deserialize arcgis geometries.  Proj4.js should handle projecting and it should be up to the user to convert spatial references either before or after using this tool.

If you think this code should remain, then I would argue that every spatial reference should be converted to the wkid 4326. It is very inconsistent to only have this happen to one spatial reference.

**Comment by jgravois** [comment]
sorry for the belated response. i tend to agree with you so i'll make sure to incorporate the suggested change during our upcoming refactor.
