### ISSUE TITLE
Converting ArcGIS Server JSON to GeoJSON (within a node project)

### ISSUE THREAD

**Issue by shawnmgoulet** [Esri/terraformer-arcgis-parser#44]
I am developing a [node](https://nodejs.org/en/) project in the [vueJS](https://vuejs.org/) framework and need to use a multipolygon service that is published to ArcGIS Server 10.31.  I need to convert it to GeoJSON to use in my web app.  I am trying to establish the best way forward to return the service as GeoJSON.

The conversion needs to happen in the web app code and not on the command line like using OGR GDAL in the command line as suggested on this gis stackexchange [post](http://gis.stackexchange.com/questions/13029/converting-arcgis-server-json-to-geojson).

From what I've gathered, my npm options are (in no particular order)

- [esri-leaflet](https://www.npmjs.com/package/esri-leaflet)
- [terraformer](https://www.npmjs.com/package/terraformer-arcgis-parser)
- [arcgis-to-geojson-utils](https://www.npmjs.com/package/arcgis-to-geojson-utils)

At the hopes of not aimlessly going down the 3 roads, could you please advise the best option for this use case?

Thanks Kindly

**Comment by jgravois** [comment]
the code in `esri-leaflet`, `terraformer-arcgis-parser` and `arcgis-to-geojson-utils` to convert back and forth between esri json and geojson is pretty much exactly the same.
 
* esri-leaflet - conversion methods bundled with other generic leaflet stuff
* terraformer/terraformer-arcgis-parser - conversion methods bundled with other generic node/browser usable utilities for spatial operations
* arcgis-to-geojson-utils - just the conversion methods

> could you please advise the best option for this use case?

if all you need to do is convert esri json to geojson and you *aren't* going to display the result in Leaflet it'd make sense to use arcgis-to-geojson-utils. there's nothing wrong with using one of the others instead, you'd just be including more dependencies.

**Comment by jgravois** [comment]
i should also mention that ArcGIS Online feature services have supported emitting GeoJSON natively for quite some time and the ArcGIS Server Map Service and Feature Service layer query operation began supporting the same at 10.41.  

http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Query_Map_Service_Layer/02r3000000p1000000/

| Parameter | Details |
| - | - |
| f | Values: html, json, geojson, kmz, amf (default, when returnIdsOnly=false and returnCountOnly=false)

Patching any install going back as far as 10.1 is a straightforward process that doesn't require republishing individual services, so I highly recommend folks take the COTS route whenever possible.

**Comment by shawnmgoulet** [comment]
Hi @jgravois - does [opendata.arcgis.com](opendata.arcgis.com) have a public repo?  If so, I'm not finding it at [Esri GitHub](https://github.com/Esri), could you help me locate it?

Since you clarified this for me, I had since been accessing the service as a geojson from [NOAA Tool dd](http://gis-cccommission.opendata.arcgis.com/datasets/38f152366141480a8f09f493587fdb2c_0) > APIs > [GeoJSON](http://gis-cccommission.opendata.arcgis.com/datasets/38f152366141480a8f09f493587fdb2c_0.geojson).  Up until last Friday, this approach was working just fine and my web app was displaying & the user could interact with & access attributes of the geojson polygons.

But as of yesterday, when I resumed working on the web app, when it attempts to access the GeoJSON, it's returning this to the Chrome Developer Tools Console (screen shot attached):

`XMLHttpRequest cannot load http://gis.cccommission.opendata.arcgis.com/datasets/38f152366141480a8f09f493587fdb2c_0.geojson. Redirect from 'http://gis.cccommission.opendata.arcgis.com/datasets/38f152366141480a8f09f493587fdb2c_0.geojson' to 'http://gis-cccommission.opendata.arcgis.com/datasets/38f152366141480a8f09f493587fdb2c_0.geojson' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.`

`[object ProgressEvent]`

I've yet to have this error and the web app was working as expected last Friday, so I was hoping to see if something happened to [opendata.arcgis.com](opendata.arcgis.com) between last Friday and now that is returning the CORS error.

![corserror](https://cloud.githubusercontent.com/assets/3179974/22937187/e1978a9e-f2a5-11e6-8ba1-08c97e2d760b.png)

**Comment by jgravois** [comment]
summoning @sidewalkballet...  

perhaps @shawnmgoulet just needs to flush the cache for that dataset somehow?

**Comment by shawnmgoulet** [comment]
Thanks @jgravois!

Would love to learn how to flush the cache for that dataset @sidewalkballet (and/or anything else that Esri could recommend).

To add a little more on to what I previously shared on this, I did go through the entire process again of:

1.  re-publishing the service to ArcServer
2.  unsharing & re-sharing the service on AGOL with [Cape Cod Commission's Open Data Portal](http://gis-cccommission.opendata.arcgis.com/)

Seems weird that I am able to download the geoJSON as a file when going to the geoJSON link provided through the Open Data API in the browser, but am returning explained above when attempting to access it in my web app.  None of my web app's code changed between working & not working (between Monday & just now).

I'm also attaching a screen shot of the web app with multipoly features working by adding the geoJSON inline in the code (which works).  As the multipolygon dataset will remain fluid, for my use case, this isn't sustainable.

![webappexampleshot](https://cloud.githubusercontent.com/assets/3179974/22982141/3882cf1e-f36c-11e6-9d76-700355a249fd.png)

**Comment by shawnmgoulet** [comment]
@sidewalkballet - I was able to publish a new&different map service and am now able to access the geoJSON in the same fashion.  All set.

**Comment by sidewalkballet** [comment]
Sounds good @shawnmgoulet. In the future - if you're an admin you can flush the cache of the dataset by hitting the 'reset downloads' button next to the dataset in your data manager page.

**Comment by hoogw** [comment]
**Converting ArcGIS JSON to GeoJSONThere in pure Browser** 

there are 2 ways you can do

**1) [TERRAFORMER][1]**

   Note: use in node.js and use in browser are **different**, details see link


**2) [Esri/arcgis-to-geojson-utils
][2]** 

Esri does not provide the bundle.js, so you can **NOT** use this lib in browser directly

As of today, you can not load module in browser.

You can only use ESIR lib in node.js, not browser.




**To use this esri lib in browser, you should use some bundler,** please follow:

a) You need to compile all the module source file into a single bundle.js

   [rollup.js][3] install by 

    npm install --global rollup

then go to your js lib root folder, find the entry point js file, in this case it is **index.js**

    $ rollup index.js --format umd --name "esri_arcgis_to_geojson" --file bundle.js

You should find a new file bundle.js in your root directory.

Now in your browser html file, include this bundle.js file
  

    <script src='.../.../.../bundle.js'>

You can use it now by

      // parse ArcGIS JSON, convert it to GeoJSON
      var geojson = esri_arcgis_to_geojson.arcgisToGeoJSON({
                                "x":-122.6764,
                                "y":45.5165,
                                "spatialReference": {
                                  "wkid": 4326
                                }
                                });
                                
     // take GeoJSON and convert it to ArcGIS JSON
      var arcgis = esri_arcgis_to_geojson.geojsonToArcGIS({
                                "type": "Point",
                                  "coordinates": [45.5165, -122.6764]
                                });enter code here

  
 



Remember **esri_arcgis_to_geojson** is the name you named the lib

This becomes the global variable name, available in browser.

The trick is, bundle process add instant implement function like (function xx {}) here is the top part from bundle.js

      (function (global, factory) {
         typeof exports === 'object' && typeof module !== 'undefined' ? 
            factory(exports) :
          typeof define === 'function' && define.amd ? define(['exports'], 
             factory) :
          (factory((global.arcgis_to_geojson = {})));
          }(this, (function (exports) { 'use strict';

             ***ORIGINAL SOURCE CODE OF JS MODULE***

         })));
    
          
[arcgis-to-geojson-utils][2]


  [1]: http://terraformer.io/arcgis-parser/
  [2]: https://github.com/Esri/arcgis-to-geojson-utils
  [3]: https://github.com/rollup/rollup

**Comment by jgravois** [comment]
> Esri does not provide the bundle.js, so you can NOT use this lib in browser directly

that's not true @hoogw. each release already includes a UMD that hydrates a `ArcgisToGeojsonUtils` namespace.

```html
<script src="https://unpkg.com/@esri/arcgis-to-geojson-utils@1.2.0/dist/arcgis-to-geojson.js"></script>
```
```js
ArcgisToGeojsonUtils.arcgisToGeoJSON({
    "x":-122.6764,
    "y":45.5165,
    "spatialReference": {
      "wkid": 4326
    }
});
```

http://jsbin.com/qaroses/edit?html,output
