### ISSUE TITLE
No console.log

### ISSUE THREAD

**Issue by cegoddard** [Esri/terraformer-arcgis-parser#45]
Include console.log in ArcGIS JSON Parser so developers do not have to manually enter into script when testing parser.

**Comment by jgravois** [comment]
can you explain in a little bit more detail what you're asking for?  in general it is considered bad form to leave stray `console.log()` statements lying around.

**Comment by cegoddard** [comment]
@jgravois in the documentation/examples there is no console.log(); folks who are new to JS, programming etc. could benefit from a // use console.log() to see results in terminal.

**Comment by jgravois** [comment]
so in [this doc page](http://terraformer.io/arcgis-parser/), you're suggesting we do something like?

```js
// parse an ArcGIS Geometry to GeoJSON
var geojsonPoint = Terraformer.ArcGIS.parse({
  "x":-122.6764,
  "y":45.5165,
  "spatialReference": {
    "wkid": 4326
  }
});

console.log(geojsonPoint);

// convert a GeoJSON object into an ArcGIS geometry
var arcgisPoint = Terraformer.ArcGIS.convert({
  "type": "Point",
  "coordinates": [45.5165, -122.6764]
});

console.log(arcgisPoint);
```
anywhere else?

**Comment by cegoddard** [comment]
Yes, that is correct. 

<img width="515" alt="code_example" src="https://cloud.githubusercontent.com/assets/20525398/23183388/b0941ad0-f830-11e6-99c1-d299335bf925.png">

**Comment by jgravois** [comment]
that sounds good to me.

the markdown for the static page on the terraformer website can be found below.

https://github.com/Esri/Terraformer/blob/master/docs/arcgis-parser.html.md

would you be willing to submit a pull request with proposed changes? if so, i'd be pleased to incorporate them.

https://guides.github.com/activities/contributing-to-open-source/

**Comment by jgravois** [comment]
we are still happy to review a PR for this anytime. but no need to track it in an open issue.
