### ISSUE TITLE
Importing module in typescript yields empty ArcGIS namespace

### ISSUE THREAD

**Issue by dgwaldo** [Esri/terraformer-arcgis-parser#46]
Perhaps I'm importing this incorrectly, but when I load the code like this

import * as Terraformer from "terraformer";
import "terraformer-arcgis-parser";

And use it like this, the ArcGIS object is undefined.

  var primitive = new Terraformer.FeatureCollection(geojson);
  var arcGisJson = Terraformer.ArcGIS.convert(primitive);

**Comment by dgwaldo** [comment]
I realized importing it as 

import * as TerraformerArcGIS from "terraformer-arcgis-parser" works.  Looks like the typescript definitions on this library could be renamed to index.d.ts as well.

**Comment by jgravois** [comment]
i'll try and find time to mimic the pattern @JeffJacobson used in Esri/Terraformer#297 here soon.

**Comment by JeffJacobson** [comment]
What I did [there](https://github.com/Esri/Terraformer/pull/297), which is the format that is preferred by [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), the source of the `@types/` definitions on NPM:

1. Remove surrounding `namespace` declarations.
2. Add the `export` keyword before each interface and type definition. In Visual Studio Code you can use a search and replace, searching for the regex `^(\w+)` and replacing with `export $1`.

**Comment by dgwaldo** [comment]
Finally got a chance to look at this again.
In package.json I've updated the dependencies to look at the latest from github.

`"dependencies": { 
     "terraformer": "git+https://github.com/Esri/Terraformer.git", 
     "terraformer-arcgis-parser": "git+https://github.com/Esri/terraformer-arcgis-parser.git", 
 },
`
Either of the following import styles now seem to work.
`import * TerraformerArcGIS from "terraformer-arcgis-parser";`
or
`import TerraformerArcGIS = require("terraformer-arcgis-parser");`

It might be helpful to include something on how to import the library when using typescript.  
Thanks!

**Comment by jgravois** [comment]
i've added a code snippet to the readme. thanks for confirming!
