### ISSUE TITLE
How to convert arcgis featureSet to geojson?

### ISSUE THREAD

**Issue by hoogw** [Esri/terraformer-arcgis-parser#49]
How to convert arcgis featureSet to geojson?

I understand this module only convert a single arcgis geometry to geojson, 

However, the response from arcgis rest api, are NOT geometry, 

instead, they are FeatureSet. 

Can you add the function to convert arcgis FeatureSet to geojson?

**Comment by jgravois** [comment]
duplicate of https://github.com/Esri/arcgis-to-geojson-utils/issues/30
